### ISSUE TITLE
go build is failing

### ISSUE THREAD

**Issue by hasan-dot** [adamroach/heapspurs#1]
I'm trying to build the project as mentioned in the readme file but its failing:

```
➜  heapspurs git:(main) go build ./cmd/heapspurs                               
cmd/heapspurs/main.go:12:2: no required module provides package github.com/adamroach/heapspurs/pkg/heapdump; to add it:
        go get github.com/adamroach/heapspurs/pkg/heapdump
```

I guess there are some missing packages or the imported packaged `github.com/adamroach/heapspurs/pkg/heapdump` is misspelled.

**Comment by adamroach** [comment]
Thanks for letting me know! I botched the `.gitignore` on initial import, which resulted in the heapdump directory being omitted. Do a `git pull` and try again.

**Comment by hasan-dot** [comment]
Thank you @adamroach it works! ✨
